about = Über
about-boxy-svg = Über Boxy SVG
accent-color = Akzentfarbe
accessibility = Zugänglichkeit
account = Konto
actions = Aktionen
activity = Aktivität
ad-hoc = Ad hoc
add = Hinzufügen
add-attribute = Attribut hinzufügen
add-bitmap-from-library = Bitmap aus Bibliothek hinzufügen
add-color = Farbe hinzufügen
add-colors = Farben hinzufügen
add-colors-from-library = Farben aus Bibliothek hinzufügen
add-colors-from-fill = Farben aus Füllung von ausgewählten Objekten hinzufügen
add-colors-from-stroke = Farben aus Kontur von ausgewählten Objekten hinzufügen
add-filter = Filter hinzufügen
add-filter-primitive = Filterbaustein hinzufügen
add-fonts = Schriftarten hinzufügen
add-fonts-from-disk = Schriftarten von der Festplatte hinzufügen
add-fonts-from-library = Schriftarten aus Bibliothek hinzufügen
add-gradient = Farbverlauf hinzufügen
add-gradient-from-fill = Farbverlauf aus Füllung von ausgewählten Objekt hinzufügen
add-gradient-from-library = Farbverlauf aus Bibliothek hinzufügen
add-gradient-from-stroke = Farbverlauf aus Kontur von ausgewählten Objekt hinzufügen
add-gradient-stop = Zwischenfarbe zum Farbverlauf hinzufügen
add-marker = Markierung hinzufügen
add-marker-from-selected-objects = Markierung von ausgewählten Objekten hinzufügen
add-node = Knoten hinzufügen
add-object = Objekt hinzufügen
add-pattern = Muster hinzufügen
add-pattern-from-selected-objects = Muster von ausgewählten Objekten hinzufügen
add-stop = Zwischenfarbe hinzufügen
add-symbol = Symbol hinzufügen
add-symbol-from-selected-objects = Symbol von ausgewählten Objekten hinzufügen
add-to-defs = Zu den Definitionen hinzufügen
add-to-defs-link = Zu den Definitionen hinzufügen (verlinken)
add-to-defs-embed = Zu den Definitionen hinzufügen (einbetten)
add-to-canvas = Zur Leinwand hinzufügen
add-vectors-from-library = Vektoren aus Bibliothek hinzufügen
algorithm = Algorithmus
alignment = Ausrichtung
align-bottom = Unten ausrichten
align-left = Links ausrichten
align-right = Rechts ausrichten
align-top = Oben ausrichten
alpha = Alpha
alphanumeric = Alphanumerisch
all-settings = Alle Einstellungen
alternative-text = Alternativer Text
ambient-light = Umgebungslicht
amount = Stärke
amplitude = Amplitude
anchor = Anker
angle = Winkel
  .random = Zufälliger
  .fixed = Fixer
anti-aliasing = Kantenglättung
app-description-short =
  <p><strong>Boxy SVG</strong> Projektziel ist es, das beste Werkzeug für die Bearbeitung von SVG-Dateien zu schaffen.</p>
  <p>Sowohl für Anfänger als auch für professionelle <strong>Web-Designer</strong> und <strong>Web-Entwickler</strong>.</p>
  <p>Auf jedem Gerät und Betriebssystem.</p>
app-description-long =
  <p>Boxy SVG Projektziel ist es, das beste Werkzeug für die Bearbeitung von SVG-Dateien zu schaffen. Sowohl für Anfänger als auch für professionelle Designer und Entwickler. Auf jedem Gerät und Betriebssystem.</p>
  <p><em>=== Kernfunktionen: ===</em></p>
  <ul>
    <li>Saubere und intuitive Benutzeroberfläche, stark inspiriert von Inkscape, Sketch und Adobe Illustrator</li>
    <li>Umfassende Unterstützung für die Bearbeitung von Objektgeometrie, Transformation, Farbe und anderen Eigenschaften auf der Leinwand</li>
    <li>Speichern in den Formaten SVG und SVGZ, Export in PNG, JPG, WebP, PDF und HTML5</li>
    <li>Integration mit Pixabay und anderen Bibliotheken mit Millionen kostenloser Stockfotos und Vektoren</li>
    <li>Integration von Google Fonts mit Hunderten von kostenlosen Schriften</li>
    <li>Konfigurierbare Tastaturkürzel für über 100 Befehle</li>
    <li>Manuelle Hilfslinien, intelligente Hilfslinien und Gitter</li>
    <li>Pfadoperationen (vereinigen, schneiden, subtrahieren, ausschließen, schließen, umkehren usw.)</li>
    <li>Anordnungsoperationen (Ausrichten an, Drehen, Spiegeln, Ordnen, Gruppieren usw.)</li>
  </ul>
  <p><em>=== Für Webentwickler: ===</em></p>
  <ul>
    <li>Chromium-basierte Rendering-Engine</li>
    <li>SVG- und CSS-Code-Inspektor ähnlich wie bei den Chrome Dev Tools</li>
    <li>Saubere SVG-Ausgabe, die IDs, Klassen, Titel und andere Metadaten beibehält</li>
    <li>Unterstützung für die Bearbeitung von SVG-Sprites</li>
  </ul>
app-description-package-notice =
  <p>Dieses Paket wird offiziell vom Boxy SVG-Entwickler veröffentlicht, gepflegt und unterstützt.</p>
app-keywords = svg, svg editor, vektor, grafik, design, zeichnen, icon, logo, illustration
array = Array
area = Bereich
aria-role = Rolle
  .default = Standard
  .alert = Alarm
  .alertdialog = Alarmdialog
  .application = Anwendung
  .article = Artikel
  .banner = Banner
  .button = Schaltfläche
  .cell = Zelle
  .checkbox = Kontrollkästchen
  .columnheader = Überschrift der Spalte
  .combobox = Combobox
  .complementary = Ergänzend
  .contentinfo = Inhaltliche Informationen
  .definition = Definition
  .dialog = Dialog
  .directory = Verzeichnis
  .document = Dokument
  .feed = Futtermittel
  .figure = Abbildung
  .form = Formular
  .graphics-document = Grafisches Dokument
  .graphics-object = Grafisches Objekt
  .graphics-symbol = Grafik-Symbol
  .grid = Gitter
  .gridcell = Rasterzelle
  .group = Gruppe
  .heading = Überschrift
  .img = Bild
  .link = Link
  .list = Liste
  .listbox = Listbox
  .listitem = Posten auflisten
  .log = Anmelden
  .main = Hauptseite
  .marquee = Festzelt
  .math = Mathematik
  .menu = Menü
  .menubar = Menüleiste
  .menuitem = Menüpunkt
  .menuitemcheckbox = Menüpunkt (Kontrollkästchen)
  .menuitemradio = Menüpunkt (Radio)
  .navigation = Navigation
  .none = Keine
  .note = Hinweis
  .option = Option
  .presentation = Präsentation
  .progressbar = Fortschrittsanzeige
  .radio = Radio
  .radiogroup = Gruppe Radio
  .region = Region
  .row = Reihe
  .rowgroup = Reihe Gruppe
  .rowheader = Zeilenkopf
  .scrollbar = Bildlaufleiste
  .search = Suche
  .searchbox = Suchfeld
  .separator = Separator
  .slider = Regler
  .spinbutton = Spin-Taste
  .status = Status
  .switch = Schalter
  .tab = Registerkarte
  .table = Tabelle
  .tablist = Registerkarte Liste
  .tabpanel = Registerkarte
  .term = Begriff
  .textbox = Textfeld
  .timer = Zeitschaltuhr
  .toolbar = Symbolleiste
  .tooltip = QuickInfo
  .tree = Baum
  .treegrid = Baumgitter
  .treeitem = Gegenstand Baum
arms = Waffen
arrangement = Anordnung
arrow = Pfeil
  .base-thickness = Dicke der Basis
  .head-thickness = Dicke des Kopfes
  .head-length = Länge des Kopfes
  .head-inset = Kopf-Einsatz
authentication = Authentifizierung
author = Autor
auto = Auto
auto-adjust-alpha = Automatische Anpassung von Alpha
auto-remove-unused-defs = Ungenutzte Definitionen automatisch entfernen
  .unpinned = Unverankert
  .all = Alle
  .none = Keine
avatar = Avatar
avatar-hint = Bild, das neben Ihren Beiträgen angezeigt werden soll.
azimuth = Azimut
back-to-form = Zurück zur Form
background = Hintergrund
  .treat-as-transparency = Diese Farbe als Transparenz behandeln
balance = Bilanz
bias = Vorurteil
billing = Rechnung
  .monthly = Monatliche
  .yearly = Jährliche
bio = Bio
bio-hint = Schreiben Sie ein oder zwei Sätze über sich selbst.
bitmaps = Bitmaps
bleed = Beschnitt
blend-mode = Mischmodus
  .normal = Normal
  .multiply = Multiplizieren
  .screen = Negativ multiplizieren
  .overlay = Überlagerung
  .darken = Abdunkeln
  .lighten = Aufhellen
  .color-dodge = Farbig abwedeln
  .color-burn = Farbig nachbelichten
  .hard-light = Grelles Licht
  .soft-light = Weiches Licht
  .difference = Differenz
  .exclusion = Ausschluss
  .hue = Farbton
  .saturation = Sättigung
  .color = Farbe
  .luminosity = Leuchtkraft
  .isolate = Isolieren
blob = Blob
blog = Blog
blur-delta = Unschärfe-Delta
blur-radius = Unschärferadius
bold = Fett
boolean-operations = Boolesche Operationen
  .unite = Vereinen
  .intersect = Schnittmenge
  .subtract = Subtrahieren
  .exclude = Ausschließen
bowing = Bogenschießen
break = Pause
break-nodes = Knoten unterbrechen
bring-all-to-front = Alle nach vorne bringen
bug = Fehler
  .open = Öffnen Sie
  .duplicate = Duplizieren
  .fixed = Festgelegt
  .wont-fix = Lässt sich nicht reparieren
  .out-of-date = Veraltet
bugs = Wanzen
  .all = Alle
  .open = Öffnen Sie
  .closed = Geschlossen
byte = Byte
byte--adjective = Byte
cache-control =
  .never-cache = Niemals zwischenspeichern
  .moderate = Mäßig
  .normal = Normal
  .aggressive = Aggressiv
  .permanent = Dauerhaft
  .custom = Benutzerdefiniert
cache-control-hint = Legen Sie den HTTP-Header "Cache-Control" fest, der den Webbrowsern mitteilt, wie sie diese Datei zwischenspeichern sollen.
caching = Caching
cancel = Abbrechen
cancel-subscription = Abonnement kündigen
cant-connect-to-server =
  Die Verbindung zum Server ist nicht möglich. Der Server ist ausgefallen oder Sie haben keine Internetverbindung. Bitte versuchen Sie es später noch einmal.
cant-edit-local-files = Lokale Dateien können nicht bearbeitet werden
  .android =
    <p><strong>Android</strong> erlaubt es Web-Apps derzeit nicht, lokale Dateien zu öffnen und zu speichern.</p>
    <p>Um Boxy SVG vollständig nutzbar zu machen, wechseln Sie bitte zu <strong>macOS</strong>, <strong>Windows</strong>, <strong>Linux</strong> oder <strong>Chrome OS</strong>.</p>
  .brave =
    <p>Der Browser<strong>Brave</strong> erlaubt es Webanwendungen nicht, lokale Dateien zu öffnen und zu speichern.</p>
    <p>Um Boxy SVG voll nutzbar zu machen, wechseln Sie bitte zu <strong>Chrome</strong>, <strong>Vivaldi</strong>, <strong>Opera</strong> oder <strong>Edge</strong> Browser.</p>
  .other =
    <p>Ihr Browser erlaubt es Webanwendungen nicht, lokale Dateien zu öffnen und zu speichern.</p>
    <p>Um Boxy SVG vollständig nutzen zu können, stellen Sie bitte sicher, dass Ihr Browser auf die neueste Version aktualisiert ist und die <strong>File System Access API</strong> in den Browsereinstellungen nicht deaktiviert ist.
canvas = Leinwand
canvas-space = Koordinatenraum der Leinwand
category = Kategorie
cell-size = Größe der Zelle
center = Zentrum
center-horizontally = Horizontal zentrieren
center-vertically = Vertikal zentrieren
center-x = Zentrum X
center-y = Zentrum Y
change = Ändern Sie
change-color = Farbe ändern
change-plan = Plan ändern
changed-subscription-plan = Geänderter Abonnementplan
  .detail = Your new plan is: {$planName}
changelog = Änderungsliste
  .added = Hinzugefügt
  .improved = Verbessert
  .fixed = Festgelegt
  .removed = Entfernt
channel = Kanal
channels = Kanäle
  .r = R
  .g = G
  .b = B
  .a = A
  .red = Rot
  .green = Grün
  .blue = Blau
  .alpha = Alpha
character = Zeichen
character-background-color = Hintergrundfarbe des Zeichens
character-color = Farbe des Zeichens
characters = Zeichen
charset = Zeichensatz
choke = Choke
circle = Kreis
class = Klasse
classes = Klassen
clear = Leeren
clear-recent = Kürzlich gelöscht
clip = Clip
clipped = Gekürzt
close = Schließen
close-path = Pfad schließen
cloud = Wolke
cloud-scope = Umfang
  .personal = Persönlich
  .org = Organisation
cloud-services = Cloud Dienste
cloud-storage-hint =
  You can keep up to 10 GB of data in the Cloud for free. Please <a href="mailto:{$email}">contact us</a>
  to get a personalized quote for a larger data package.
code = Code
code-block = Code-Block
code-snippets = Codeschnipsel
cog = Kogge
  .splay = Spreizen
  .teeth = Zähne
color = Farbe
  .auto = Auto
  .custom = Benutzerdefiniert
  .blue = Blau
  .purple = Lila
  .pink = Rosa
  .red = Rot
  .orange = Orange
  .yellow = Gelb
  .green = Grün
  .graphite = Graphit
color-id = Farbe ID
color-quantization = Quantisierung der Farbe
color-scheme = Farbschema
  .auto = Auto
  .light = Helles
  .dark = Dunkles
color-title = Farbe Titel
colors = Farben
columns = Spalten
command = Befehl
commands = Befehls
comment = Kommentar
comments = Kommentare
complexify = Komplizieren
complexify-path = Pfad komplizieren
component-transfer-type =
  .identity = Identität
  .linear = Linear
  .gamma = Gamma
  .table = Tabelle
  .discrete = Diskrete Tabelle
composite-operator =
  .over = Über
  .in = Unter
  .atop = Unter
  .out = Aus
  .xor = Xoder
  .arithmetic = Arithmetik
compositing = Komposition
compression = Kompression
cone-angle = Kegelwinkel
confirm = Bestätigen
confirm-access-to-file = Confirm access to "{$fileName}"
  .detail = Um diese Datei bearbeiten zu können, müssen Sie den Zugang zu ihr bestätigen.
confirm-clear-history = Möchten Sie den Verlauf löschen?
  .detail = Diese Aktion kann nicht rückgängig gemacht werden.
confirm-convert-shape-to-path = Form in Pfad umwandeln?
  .detail = Diese Form muss in einen Pfad umgewandelt werden, bevor Sie sie mit einem Text versehen.
confirm-delete-colors =
  Delete {$colorsCount ->
    [one] a color
   *[other] {$colorsCount} colors
  } applied to {$objectsCount} {$objectsCount ->
    [one] object
   *[other] objects
  }?
  .detail = Wenn Sie eine Farbe löschen, wird sie auch aus allen Objekten entfernt, auf die sie angewendet wurde.
confirm-delete-comment = Kommentar löschen?
  .detail = Diese Aktion kann nicht rückgängig gemacht werden.
confirm-delete-files =
  {$filesCount} {$filesCount ->
    [one] Datei
   *[other] Dateien
  } löschen?
  .detail = Diese Aktion kann nicht rückgängig gemacht werden.
confirm-delete-filters =
  {$filtersCount ->
    [one] Filter löschen, der von {$objectsCount} {$objectsCount ->
      [one] Objekt
     *[other] Objekte
    } verwendet ist?
   *[other] {$filtersCount} Filter löschen, die von {$objectsCount} {$objectsCount ->
      [one] Objekt
     *[other] Objekte
    } verwendet sind?
  }
  .detail = Wenn Sie einen Filter löschen, wird er auch von allen Objekten entfernt, auf die er angewendet wurde.
confirm-delete-fonts =
  Delete {$fontsCount ->
    [one] a font
   *[other] {$fontsCount} fonts
  } applied to {$objectsCount} {$objectsCount ->
    [one] text object
   *[other] text objects
  }?
  .detail = Wenn Sie eine Schrift löschen, wird sie auch aus allen Textobjekten entfernt, auf die sie angewendet wurde.
confirm-delete-gradients =
  Delete {$gradientsCount ->
    [one] a gradient
   *[other] {$gradientsCount} gradients
  } applied to {$objectsCount} {$objectsCount ->
    [one] object
   *[other] objects
  }?
  .detail = Wenn Sie einen Farbverlauf löschen, wird er auch von allen Objekten entfernt, auf die er angewendet wurde.
confirm-delete-patterns =
  Delete {$patternsCount ->
    [one] a pattern
   *[other] {$patternsCount} patterns
  } applied to {$objectsCount} {$objectsCount ->
    [one] object
   *[other] objects
  }?
  .detail = Wenn Sie ein Muster löschen, wird es auch aus allen Objekten entfernt, auf die es angewendet wurde.
confirm-delete-markers =
  Delete {$markersCount ->
    [one] a marker
   *[other] {$markersCount} markers
  } applied to {$objectsCount} {$objectsCount ->
    [one] object
   *[other] objects
  }?
  .detail = Wenn Sie eine Markierung löschen, wird sie auch von allen Objekten entfernt, auf die sie angewendet wurde.
confirm-delete-symbols =
  Delete {$symbolsCount ->
    [one] a symbol
   *[other] {$symbolsCount} symbols
  } with {$instancesCount} {$instancesCount ->
    [one] instance
   *[other] instances
  }?
  .detail = Beim Löschen eines Symbols werden auch alle seine Instanzen entfernt.
confirm-delete-post = Beitrag löschen?
  .detail = Diese Aktion kann nicht rückgängig gemacht werden.
confirm-override-font-family = Override "{$family}" font family?
  .detail = Diese Schriftfamilie ist bereits definiert; wenn Sie sie erneut hinzufügen, wird die bestehende Definition überschrieben.
confirm-password = Bestätigen Sie das Passwort
  .detail = Bitte geben Sie Ihr aktuelles Passwort ein, um fortzufahren.
confirm-save-changes = Do you want to save the changes you made to "{$fileName}"?
  .detail = Ihre Änderungen gehen verloren, wenn Sie sie nicht speichern.
confirm-unlink-font-family = Unlink "{$familyName}" font family?
  .detail =
    Diese Schriftfamilie wird heruntergeladen und in die aktuell bearbeitete SVG-Datei eingebettet. Dieser Vorgang kann die Dateigröße Ihrer SVG-Datei erheblich vergrößern.
connect-filter-primitives = Filterbausteine verbinden
contact = Kontakt
contact-hint = Fill the form below or send an email to <a href="mailto:{$email}">{$email}</a>.
content = Inhalt
contour = Kontur
convert = Konvertieren
convert-glyphs-to-separate-paths = Jede Textglyphe in einen separaten Pfad konvertieren
convert-to-ad-hoc-color = In ad hoc Farbe umwandeln
convert-to-ad-hoc-gradient = In ad hoc Gradient umwandeln
convert-to-custom-filter = In benutzerdefinierte Filter umwandeln
coords = Koordinaten
  .x = X
  .y = Y
  .z = Z
  .x1 = X1
  .y1 = Y1
  .x2 = X2
  .y2 = Y2
copy = Kopieren
copy-link = Link kopieren
copy-outer-svg = Äußere svg kopieren
corner = Ecke
corner-radius = Eckenradius
  .top-left = Oben links
  .top-right = Oben rechts
  .bottom-left = Unten links
  .bottom-right = Unten rechts
create = Erstellen
created-by-me = Von mir erstellt
created-time = Erstellte Zeit
crescent = Mondsichel
  .arch = Arch
  .hollow = Hohle
crop-marks = Schnittmarken
cross = Kreuz
  .arm-thickness = Dicke des Arms
  .arm-1-thickness = Arm 1 Dicke
  .arm-2-thickness = Arm 2 Dicke
current-plan = Aktueller Plan
custom-filters = Benutzerdefinierte Filter
custom-thickness = Benutzerdefinierte Dicke
cut = Ausschneiden
cycles = Zyklen
dash = Gedankenstrich
date = Datum
date-abs = {DATETIME($date, day: "numeric", month: "long", year: "numeric")}
date-rel = {RELDATETIME($date)}
date-created = erstellt {RELDATETIME($date)}
date-wrote = schrieb {RELDATETIME($date)}
decoration = Dekoration
decrease = Verringern Sie
decrease-indent = Einzug verkleinern
defs = Definitionen
delete = Löschen
delete-account = Konto löschen
delete-account-hint =
  Sobald Sie Ihr Konto löschen, gibt es <strong>kein Zurück</strong> mehr. Alle Ihre Dateien werden von den Servern von boxy-svg.com entfernt. Ihr bezahltes Abonnement wird gekündigt, falls Sie eines haben.
delete-connector = Verbinder löschen
delete-filter = Filter löschen
delete-filter-primitive = Filterbaustein löschen
delete-gradient-stop = Zwischenfarbe des Farbverlaufs löschen
delete-gradient-stops = Zwischenfarben des Farbverlaufs löschen
delete-nodes = Knoten löschen
delete-primitive = Primitiv löschen
delete-stops = Zwischenfarben löschen
delta = Delta
delta-x = Delta X
delta-y = Delta Y
depth = Tiefe
description = Beschreibung
deselect-all = Auswahl aufheben
desktop-app = Desktop-Anwendung
developer = Entwickler
diffuse-constant = Diffuse Konstante
diffuse-light = Diffuse Beleuchtung
disconnect-filter-primitives = Filterbausteine abtrennen
distance = Distanz
distribute-horizontally = Horizontal verteilen
distribute-vertically = Vertikale Verteilung
distribute-centers-horizontally = Verteilung der Zentren in horizontaler Richtung
distribute-centers-vertically = Vertikale Verteilung der Zentren
distribution = Verteilung
distribution-distance = Verteilungsdistanz
  .auto = Auto
  .manual = Handbuch
dithering = Dithering
  .none = Keine
  .floyd-steinberg = Floyd-Steinberg
  .false-floyd-steinberg = Falscher Floyd-Steinberg
  .stucki = Stucki
  .atkinson = Atkinson
divisor = Divisor
docks = Docks
dont-save = Nicht speichern
dont-show-again = Nicht mehr anzeigen
download-on-flathub = Herunterladen auf <strong>Flathub</strong>
download-on-mac-app-store = Herunterladen aus dem <strong>Mac App Store</strong>
download-on-snap-store = Herunterladen aus dem <strong>Snap Store</strong>
downvote = Runterwählen
dpi = DPI
drawing = Zeichnung
drawing-mode = Zeichenmodus
  .planar = Planar
  .polar = Polar
  .three-point = 3-Punkt
draw-as = Zeichnen als
  .ellipse = Ellipse
  .circle = Kreis
  .path = Pfad
  .polyline-or-polygon = Polylinie oder Polygon
  .line-polyline-or-polygon = Linie, Polylinie oder Polygon
duplicate = Duplizieren
duplicate-filter-primitive = Duplizieren von Filterbausteinen
duplicate-gradient-stop = Zwischenfarbe des Farbverlaufs duplizieren
duplicate-gradient-stops = Zwischenfarben des Farbverlaufs duplizieren
duplicate-primitive = Filterbaustein duplizieren
duplicate-stops = Zwischenfarben duplizieren
dynamics = Dynamics
edge-mode = Kantenmodus
  .none = Keiner
  .duplicate = Duplizieren
  .wrap = Umbrechen
edit = Bearbeiten
edit--verb = Bearbeiten
edit-attribute = Attribut bearbeiten
edit-bug = Fehler bearbeiten
edit-comment = Kommentar bearbeiten
edit-custom-filter = Benutzerdefinierten Filter bearbeiten
edit-element-content = Elementinhalt bearbeiten
edit-filter = Filter bearbeiten
edit-id = ID bearbeiten
edit-idea = Idee bearbeiten
edit-post = Beitrag bearbeiten
edit-profile = Profil bearbeiten
edit-question = Frage editieren
edit-style = Stil bearbeiten
edit-text = Text bearbeiten
edit-title = Titel bearbeiten
editors-choice = Wahl des Herausgebers
elements = Elemente
elevation = Erhebungen
ellipse = Ellipse
email = E-mail
email-already-registered = Die E-Mail Adresse ist bereits registriert
email-hint = E-Mail-Adresse, die zum Anmelden und zur Wiederherstellung des Passworts verwendet wird.
emoji-category =
  .all = Alle
  .smileys-and-emotions = Smileys &amp; Emotionen
  .people-and-body = Menschen &amp; Körper
  .animals-and-nature = Tiere und Natur
  .food-and-drinks = Essen &amp; Trinken
  .travel-and-places = Reisen &amp; Orte
  .activities = Aktivitäten
  .objects = Objekte
  .symbols = Symbole
  .flags = Flaggen
end-angle = Endwinkel
end-point = Endpunkt
end-x = Ende X
end-y = Ende Y
enter = Eingabe
enter-group = Gruppe eingeben
enter-your-password-here = Geben Sie Ihr Passwort ein
enter-your-search-query = Geben Sie Ihre Suchanfrage ein
enter-your-text-here = Geben Sie hier Ihren Text ein
erase = löschen
error-correction = Fehlerkorrektur
exit = Ausfahrt
exponent = Exponent
export = Exportieren
export--verb = Exportieren
export-to-disk = Auf Festplatte exportieren
failed-to-log-in = Anmelden fehlgeschlagen
failed-to-register-account = Konto konnte nicht registriert werden
failed-to-delete-account = Konto konnte nicht gelöscht werden
failed-to-change-email = E-Mail kann nicht geändert werden
failed-to-change-password = Passwortänderung fehlgeschlagen
failed-to-change-user-name = Änderung des Benutzernamens fehlgeschlagen
failed-to-change-user-website = Benutzer-Website kann nicht geändert werden
failed-to-change-user-bio = Änderung der Benutzerbiographie fehlgeschlagen
failed-to-change-users = Benutzerwechsel fehlgeschlagen
failed-to-change-subscription-plan = Änderung des Abonnementplans fehlgeschlagen
failed-to-reset-password = Passwort kann nicht zurückgesetzt werden
failed-to-confirm-password = Passwort kann nicht bestätigt werden
failed-to-send-verification-email = Bestätigungs-E-Mail konnte nicht gesendet werden
failed-to-add-comment = Neuer Kommentar konnte nicht hinzugefügt werden
failed-to-edit-comment = Kommentar kann nicht bearbeitet werden
failed-to-delete-comment = Kommentar konnte nicht gelöscht werden
failed-to-add-post = Beitrag kann nicht hinzugefügt werden
failed-to-move-post = Beitrag nicht verschoben
failed-to-edit-post = Beitrag kann nicht bearbeitet werden
failed-to-delete-post = Beitrag konnte nicht gelöscht werden
failed-to-change-post-tags = Beitrags-Tags konnten nicht geändert werden
failed-to-change-post-priority = Änderung der Postpriorität fehlgeschlagen
failed-to-change-post-status = Änderung des Poststatus fehlgeschlagen
failed-to-watch-post = Beitrag wurde nicht angezeigt
failed-to-unwatch-post = Beitrag konnte nicht abgeschaltet werden
failed-to-upvote-post = Beitrag konnte nicht hochgewählt werden
failed-to-downvote-post = Beitrag kann nicht runtergewählt werden
failed-to-unvote-post = Beitrag nicht entvoten können
failed-to-star-post = Beitrag wurde nicht gestartet
failed-to-unstar-post = Beitrag kann nicht entsternt werden
failed-to-open-file = Datei konnte nicht geöffnet werden
  .file-not-found = File was not found on the server or some other server error occoured ({$serverError}).
failed-to-write-file = Datei kann nicht geschrieben werden
  .user-offline = Die Verbindung zum Cloud-Speicher kann nicht hergestellt werden, da Ihr Computer offline ist. Bitte versuchen Sie es später.
  .trial-expired = Die Probezeit ist abgelaufen. Bitte abonnieren Sie einen kostenpflichtigen Plan.
  .subscription-expired = Ihr bestehendes Abonnement ist abgelaufen. Bitte abonnieren Sie erneut ein kostenpflichtiges Abo.
  .user-not-subscribed = Bitte abonnieren Sie einen kostenpflichtigen Tarif.
  .user-not-subscribed-to-premium-plan = Bitte abonnieren Sie den "Premium" Plan.
  .user-not-authorized = Diese Datei wurde von einem anderen Benutzer erstellt.
  .filesystem-permission-denied = Boxy SVG hat nicht die Berechtigung, auf diese Datei zuzugreifen.
failed-to-create-file-from-clipboard = Datei aus der Zwischenablage kann nicht erstellt werden
  .detail = Der aktuelle Inhalt der Zwischenablage kann nicht zum Erstellen einer neuen Datei verwendet werden.
failed-to-create-file-from-selected = Feld zum Erstellen einer Datei aus ausgewählten Objekten
  .detail = Sie müssen mindestens ein Objekt auswählen, um daraus eine neue Datei zu erstellen.
failed-to-download-from-library = Das ausgewählte Objekt konnte nicht aus der Bibliothek heruntergeladen werden
failed-to-import-file = Datei konnte nicht importiert werden
  .ai-with-no-pdf-data =
    Dies ist eine Adobe® Illustrator®-Datei, die ohne PDF-Inhalt gespeichert wurde. Um diese Datei in andere Anwendungen zu importieren, muss sie erneut in Adobe Illustrator gespeichert werden, wobei die Option "PDF-kompatible Datei erstellen" aktiviert sein muss.
failed-to-change-file-cache-control = Cache-Control-Header der Datei konnte nicht geändert werden
failed-to-change-file-library = Die Bibliothek konnte nicht geändert werden
failed-to-rename-file = Datei kann nicht umbenannt werden
failed-to-delete-file = Datei konnte nicht gelöscht werden
failed-to-move-files = Dateien können nicht verschoben werden
failed-to-create-folder = Ordner konnte nicht erstellt werden
failed-to-rename-folder = Ordner kann nicht umbenannt werden
failed-to-add-font = Schrift kann nicht hinzugefügt werden
  .unsupported-format = Nicht unterstütztes Schriftformat.
failed-to-refresh-fonts-list = Aktualisierung der Liste der Schriften fehlgeschlagen
failed-to-convert-text-to-path = Konvertierung von Text in Pfad fehlgeschlagen
  .no-permission = Um diesen Vorgang durchzuführen, müssen Sie Boxy SVG zunächst die Erlaubnis erteilen, auf Ihre lokalen Schriften zuzugreifen.
  .no-api = Ihr Browser unterstützt die <a href="https://boxy-svg.com/blog/15">Local Font Access API</a> nicht.
  .no-font = Die für diesen Text verwendete Schrift wurde weder in den Definitionen noch auf dem lokalen Rechner gefunden.
failed-to-send-contact-message = Nachricht konnte nicht gesendet werden
fetching = Abrufbar unter
file = Datei
  .edited = Bearbeitet
  .imported = Importiert
  .untitled = Unbetitelt
fill = Füllung
fill-color = Füllfarbe
fill-opacity = Deckkraft der Füllung
fill-rule = Regel für die Füllung
  .non-zero = Nicht-Null
  .even-odd = Gerade/ungerade
filter = Filter
filter-id = Filter ID
filter-primitive = Filterbaustein
  .connector = Verbinder
  .source-graphic = Quellgrafik
  .source-alpha = Alphakanal der Quelle
  .blend = Mischung
  .composite = Kombinieren
  .merge = Zusammenführen
  .flood = Füllen
  .image = Bild
  .tile = Kacheln
  .turbulence = Turbulenz
  .color-matrix = Farbmatrix
  .component-transfer = Komponenten-Übertragung
  .convolve-matrix = Faltungsmatrix
  .displacement-map = Versatzkarte
  .gaussian-blur = Gaußscher Weichzeichner
  .morphology = Morphologie
  .drop-shadow = Schlagschatten
  .offset = Versatz
  .specular-lighting = Punktlicht
  .diffuse-lighting = Diffuse Beleuchtung
filter-title = Titel filtern
filter-units = Filtereinheiten
filters = Filter
file-size = Dateigröße
file-size-bytes-suffix = {$count ->
  [one] byte
 *[other] bytes
}
flip-x = Umdrehen X
flip-y = Umdrehen Y
font = Schrift
  .family = Familie
  .face = Gesicht
  .weights = Gewichte
  .subsets = Untergruppen
font-category = Kategorie
  .all = Alle
  .sans-serif = Serifenlose Schrift
  .serif = Serif
  .display = Anzeige
  .handwriting = Handschrift
  .monospace = Monospace
font-family = Schriftfamilie
font-size = Schriftgröße
font-stretch =
  .ultra-condensed = Ultra-kondensiert
  .extra-condensed = Extra-kondensiert
  .condensed = Kondensiert
  .semi-condensed = Halbkondensiert
  .normal = Normal
  .semi-expanded = Halbexpandiert
  .expanded = Erweitert
  .extra-expanded = Extra-erweitert
  .ultra-expanded = Ultra-expandierte
font-style = Schriftstil
  .normal = Normal
  .italic = Kursiv
  .oblique = Schräg
font-subset = Teilmenge
  .all = Alle
  .arabic = Arabisch
  .bengali = Bengalisch
  .chinese-hongkong = Chinesisch (Hongkong)
  .chinese-simplified = Chinesisch (vereinfacht)
  .chinese-traditional = Chinesisch (traditionell)
  .cyrillic = Kyrillisch
  .cyrillic-ext = Kyrillisch (erweitert)
  .devanagari = Devanagari
  .greek = Griechisch
  .greek-ext = Griechisch (erweitert)
  .gujarati = Gujarati
  .gurmukhi = Gurmukhi
  .hebrew = Hebräisch
  .japanese = Japanisch
  .kannada = Kannada
  .khmer = Khmer
  .korean = Koreanisch
  .latin = Lateinisch
  .latin-ext = Latein (erweitert)
  .malayalam = Malayalam
  .myanmar = Myanmar
  .oriya = Oriya
  .sinhala = Singhalesisch
  .tamil = Tamilisch
  .thai = Thailändisch
  .telugu = Telugu
  .tibetan = Tibetisch
  .vietnamese = Vietnamesisch
font-weight = Gewicht der Schrift
  .named-100 = Dünn
  .named-200 = Extra-leicht
  .named-300 = Licht
  .named-400 = Normal
  .named-500 = Mittel
  .named-600 = Halbfettdruck
  .named-700 = Kühn
  .named-800 = Extrafett
  .named-900 = Ultrafett
  .synthesized = Synthetisiert
fonts = Schriften
fonts-from-defs = Schriften aus Definitionen
format = Format
frame = Rahmen
freehand = Freihand
frequency = Frequenz
fullscreen-mode = Vollbildmodus
gamma-correction = Gammakorrektur
garbage-collector = Müllsammler
general = Allgemeine
generate = Erzeugen
geometry = Geometrie
geometry-precision = Präzision der Geometrie
geometry-precision-hint = Genauigkeit in Form von Dezimalstellen, die von Attributen zur Definition der Formgeometrie wie <code>x</code>, <code>y</code>, <code>width</code>, <code>height</code>, <code>r</code> oder <code>d</code> zu verwenden ist.
generate-random-colors = Zufällige Farben generieren
generating-preview = Vorschau generieren
generators = Generatoren
  .barcode = Barcode
  .qr-code = QR-Code
  .parliament-chart = Diagramm des Parlaments
  .triangulated-surface = Dreieckige Oberfläche
  .fire = Feuer
  .jigsaw-puzzle = Puzzle
  .rasterize = Rasterisieren
  .vectorize = Vektorisieren
  .pixelate = Pixelieren
  .triangulate = Triangulieren
  .asciify = Asciieren
  .primitivize = Primitivisieren
  .sketchify = Skizzieren
  .printing-marks = Druckmarken
  .resize-view-to-fit-objects = Ansicht an Objekte anpassen
  .add-unique-ids = Eindeutige IDs hinzufügen
get-boxy-svg = Boxy SVG erhalten
glyph-rotation = Glyphen-Drehung
grab = Greifen
grab-paint-color = Farbe greifen
gradient = Farbverlauf
gradient-id = Gradient ID
gradient-spread = Überlauf
  .pad = Pad
  .repeat = Wiederholen
  .reflect = Reflektieren
gradient-title = Gradient Titel
gradients = Farbverläufe
grid = Gitter
group = Gruppe
group--verb = Gruppieren
grouping = Gruppierung
guide = Hilfslinien
guides = Hilfslinien
hardware-acceleration = Hardware-Beschleunigung
hardware-acceleration-hint =
  Sie sollten die Hardwarebeschleunigung deaktivieren, wenn Sie die Anwendung in einer virtuellen Maschine oder auf älterer Hardware ausführen und Sie grafische Störungen wie Flackern oder verschwindende Widgets beobachten. <strong>Erfordert einen Neustart der App.</strong>
harmonize = Harmonisieren Sie
harmonize-gradient = Gradient harmonisieren
hatching = Schraffur
hatching-type =
  .zigzag = Zickzack
  .grid = Gitter
  .straight-lines = Gerade Linien
  .zigzag-lines = Zickzack-Linien
  .dots = Dots
  .dashes = Bindestriche
  .solid = Solide
heading = Überschrift
height = Höhe
help = Hilfe
hide = Ausblenden
hide-boxy-svg = Boxy SVG ausblenden
hide-others = Andere ausblenden
highlight = Highlight
highlights-color = Highlights Farbe
history = Protokoll
home = Startseite
homepage = Offizielle Website
hue-rotation = Farbtondrehung
icon = Ikone
  .normal = Normal
  .monochromatic = Monochromatische
icons = Icons
icon-variant = Variante
  .all = Alle
  .regular = Regelmäßig
  .filled = Gefüllt
  .outlined = Skizziert
  .rounded = Gerundet
  .sharp = Scharf
  .two-tone = Zweiton
id = ID
idea = Idee
  .open = Öffnen Sie
  .duplicate = Duplizieren
  .done = Erledigt
  .rejected = Abgelehnt
  .out-of-date = Veraltet
ideas = Ideen
  .all = Alle
  .open = Öffnen Sie
  .closed = Geschlossen
image = Bild
import = Importieren
import-from-disk = Importieren von Diskette
import-from-url = Von URL importieren
increase = Erhöhung
increase-indent = Einzug vergrößern
indentation = Vertiefung
indentation-hint = Anzahl der Leerzeichen, die zum Einrücken von SVG-Code verwendet werden.
inherit = Erben Sie
inner-radius = Innenradius
inner-radius-x = Innenradius X
inner-radius-y = Innenradius Y
input-slot = Eingabeschlitz
inset = Einlage
inset--verb = Einlage
inset-path = Eingeschobener Pfad
inspect = Überprüfen Sie
install = Installieren
install-boxy-svg = Boxy SVG installieren
install-boxy-svg-hint =
  Boxy SVG ist als <strong>PWA (Progressive Web App)</strong> verfügbar, die auf Ihrem Computer installiert und wie eine normale Desktop-App verwendet werden kann.
intercept = Abfangen
internal-server-error = Interner Serverfehler, bitte versuchen Sie es später
italic = Kursiv
invalid-color = Ungültige Farbe
invalid-email = Ungültige E-Mail
invalid-id = Ungültige ID
invalid-name = Ungültiger Name
invalid-prefix = Ungültige Vorsilbe
invalid-url = Ungültige URL
i-agree-to-tos-and-privacy-policy =
  Ich stimme den <a href="/legal#web-app-terms">Nutzungsbedingungen</a> und der <a href="/legal#web-app-privacy">Datenschutzrichtlinie</a> zu.
jitter = Zufallswert
join = Beitreten
join-nodes = Knoten verbinden
join-paths = Pfade verbinden
kanji = Kanji
kernel = Kernel
keyboard = Tastatur
label = Etikett
language = Sprache
  .auto = Auto
  .unknown = Unbekannte
  .af = Afrikaans
  .sq = Albanisch
  .ar = Arabisch
  .hy = Armenisch
  .az = Aserisch
  .eu = Baskisch
  .be = Weißrussisch
  .bg = Bulgarisch
  .ca = Katalanisch
  .zh = Chinesisch
  .hr = Kroatisch
  .cs = Tschechisch
  .da = Dänisch
  .nl = Niederländisch
  .en = Englisch
  .et = Estnisch
  .fa = Farsi
  .fi = Finnisch
  .fr = Französisch
  .gl = Galicisch
  .de = Deutsch
  .ka = Georgisch
  .el = Griechisch
  .he = Hebräisch
  .hi = Hindi
  .hu = Ungarisch
  .is = Isländisch
  .id = Indonesisch
  .it = Italienisch
  .ja = Japanisch
  .kk = Kasachisch
  .ko = Koreanisch
  .lv = Lettisch
  .lt = Litauisch
  .mt = Maltesisch
  .mn = Mongolisch
  .nb = Norwegisch
  .pl = Polnisch
  .pt = Portugiesisch
  .ro = Rumänisch
  .ru = Russisch
  .sk = Slowakisch
  .sl = Slowenisch
  .es = Spanisch
  .sv = Schwedisch
  .th = Thailändisch
  .tr = Türkisch
  .uk = Ukrainisch
  .ur = Urdu
  .uz = Usbekisch
  .vi = Vietnamesisch
  .cy = Walisisch
launch-app = App starten
legal = Rechtliches
length = Länge
letter-spacing = Buchstabenabstand
library = Bibliothek
library-category =
  .all = Alle
  .action = Aktion
  .alert = Alarm
  .animals = Tiere
  .av = Audio & video
  .backgrounds = Hintergründe
  .buildings = Gebäude
  .business = Unternehmen
  .communication = Kommunikation
  .computer = Computer
  .content = Inhalt
  .design = Design
  .development = Entwicklung
  .device = Gerät
  .document = Dokument
  .editor = Editor
  .education = Bildung
  .fashion = Mode
  .feelings = Gefühle
  .file = Datei
  .finance = Finanzen
  .food = Lebensmittel
  .hardware = Hardware
  .health = Gesundheit
  .home = Zuhause
  .image = Bild
  .industry = Wirtschaft
  .logos = Logos
  .maps = Karten
  .media = Medien
  .music = Musik
  .nature = Natur
  .navigation = Navigation
  .notification = Benachrichtigung
  .others = Andere
  .people = Menschen
  .places = Orte
  .religion = Religion
  .science = Wissenschaft
  .search = Suche
  .social = Sozial
  .sports = Sport
  .system = System
  .toggle = Umschalten
  .transportation = Transport
  .travel = Reisen
  .user = Benutzer
  .weather = Wetter
library-scope =
  .none = Keine
  .personal = Persönlich
  .organization = Organisation
  .none-detail = Zeigen Sie diese Datei nicht im Fenster "Bibliothek" an.
  .personal-detail = Zeigen Sie diese Datei nur mir.
  .organization-detail = Zeigen Sie diese Datei allen Benutzern, die zu meiner Organisation gehören.
libraries = Bibliotheken
license = Lizenz
light-source = Lichtquelle
  .point = Punkt
  .spot = Punkt
  .distant = Entfernte
limiting-cone-angle = Begrenzter Kegelwinkel
limit-scrollable-area = Begrenzung des scrollbaren Bereichs
linear-gradient = Lineare Steigung
line = Linie
  .cap = Enendung
  .join = Zusammentreffen
line-cap = Linienendung
  .butt = Stumpf
  .round = Rund
  .square = Rechteckig
line-join = Linienzusammentreffen
  .miter = Gehrung
  .round = Rund
  .bevel = Abgeschrägte Kante
line-spacing = Zeilenabstand
link = Link
link--verb = Verbinden
live-demo = Live-Demo
live-demo-hint = Klicken Sie auf die Miniaturansicht einer SVG-Datei, um sie mit dem Boxy SVG Editor zu öffnen.
local-fonts = Lokale Schriften
lock = Fixieren
log-in = Anmelden
log-out = Abmelden
luminance-to-alpha = Luminanz zu Alpha
machine-translation = Maschinelle Übersetzung
manage = Verwalten Sie
manage-your-subscription = Verwalten Sie Ihr <strong>Abonnement</strong>
manual-guides = Manuelle Hilfslinien
margin = Marge
marker = Markierung
  .start = Start
  .mid = Mitte
  .end = Ende
marker-id = Markierungs-ID
marker-title = Titel der Markierung
markers = Markierungen
markup = Auszeichnung
mask = Maske
masked = Maskiert
masking = Maskierung
matrix = Matrix
max-mutations = Maximale Mutationen
menubar = Menüleiste
merge-all-windows = Alle Fenster zusammenführen
message = Nachricht
message-sent = Nachricht gesendet
  .detail = Wir werden uns innerhalb der nächsten 48 Stunden mit Ihnen in Verbindung setzen.
meta = Meta
minimize = minimieren.
minimize-window = Weite minimieren
maximize = Maximieren Sie
min-ratio = Min. Verhältnis
missing-id = Fehlende ID
miter-limit = Gehrungsgrenze
mode = Modus
modifier-keys = Modifier-Tasten
morphology-operator =
  .dilate = Ausweiten
  .erode = Erodieren
move = Verschieben
move-control-points = Kontrollpunkte verschieben
move-cursor-over-object = Cursor über das Objekt bewegen
move-gradient-stop = Zwischenfarbe des Farbverlaufs verschieben
move-gradient-stops = Zwischenfarben des Farbverlaufs verschieben
move-nodes = Knoten verschieben
move-objects-with-view = Objekte mit Ansicht verschieben
move-post = Posten verschieben
  .detail = Der Beitrag erhält eine neue eindeutige ID und einen neuen Pfad, während der alte Pfad in eine einfache Weiterleitung umgewandelt wird.
move-transform-origin = Transformationsursprung verschieben
move-tab-to-new-window = Registerkarte in neues Fenster verschieben
n-gon = N-Gon
name = Name
name-hint = Ihr richtiger Name oder ein Spitzname.
name-already-taken = Dieser Name ist bereits vergeben
natural-size = Natürliche Größe
new = Neu
new-bug = Neuer Fehler
new-category = Neue Kategorie
new-comment = Neuer Kommentar
new-file = Neue Datei
new-folder-with-selection = Neuer Ordner mit Auswahl
new-from-clipboard = Neu aus der Zwischenablage
new-from-selected = Neu von ausgewählten
new-from-url = Neu von URL
new-idea = Neue Idee
new-post = Neue Stelle
new-question = Neue Frage
node = Knotenpunkt
nodes = Knotenpunkte
noise = Rauschen
none = Keine
non-unique-id = Nicht eindeutige ID
normalize = Normalisieren
  .convert-texts-to-paths = Texte in Pfade umwandeln
  .remove-embedded-fonts = Eingebettete Schriften entfernen
  .remove-non-standard-namespaces = Nicht standardisierte Namensräume entfernen
  .remove-hidden-objects = Ausgeblendete Objekte entfernen
no-bitmaps-found = Keine Bitmaps gefunden
no-colors-found = Keine Farben gefunden
no-commands-found = Keine Befehle gefunden
no-filter-primitive-options = Dieses Primitiv hat keine Optionen
no-filters = Keine Filter
no-filters-found = Keine Filter gefunden
no-fonts-found = Keine Schriftarten gefunden
no-gradients-found = Keine Gradienten gefunden
no-gradient-stops-selected = Keine Steigungsstopps ausgewählt
no-history-items = Keine historischen Elemente
no-local-fonts-api = Ihr Browser unterstützt den <a href="https://boxy-svg.com/blog/15">Zugriff auf lokale</a> Schriften nicht
no-local-fonts-permission = <a href="">Klicken Sie hier</a>, um Boxy SVG die Erlaubnis zu erteilen, Ihre lokalen Schriften zu verwenden
no-markers-found = Keine Marker gefunden
no-patterns-found = Keine Muster gefunden
no-results = Keine Ergebnisse
no-symbols-found = Keine Symbole gefunden
no-vectors-found = Keine Vektoren gefunden
number = Nummer
number-of-octaves = Anzahl der Oktaven
numeric = Numerisch
object = Objekt
object-id = Objekt-ID
object-title = Titel des Objekts
objects = Objekte
  .all = Alle
  .selected = Ausgewählte
offset = Versatz
offset-x = X Versatz
offset-y = Y Versatz
opacity = Deckkraft
  .fixed = Festgelegt
  .random = Zufällig
open = Öffnen
open-from-cloud = Aus der Wolke öffnen
open-from-disk = Von Diskette öffnen
open-in-new-tab = In neuer Registerkarte öffnen
open-path = Pfad öffnen
open-recent = Zuletzt geöffnet
open-with-boxy-svg = Öffnen mit Boxy SVG ⧉
open-with-web-browser = Mit Webbrowser öffnen ⧉
operator = Betreiber
options = Optionen
order = Bestellung
  .lower = Unter
  .lower-to-back = Unten nach hinten
  .raise = Erhöhen Sie
  .raise-to-front = Nach vorne anheben
  .back = Zurück
  .front = Vorderseite
ordered-list = Geordnete Liste
orientation = Ausrichtung
  .all = Alle
  .horizontal = Horizontal
  .vertical = Vertikal
origin = Herkunft
  .auto = Auto
origin-x = Herkunft X
origin-y = Herkunft Y
other-shape = Andere Form
outer-radius = Äußerer Radius
outer-radius-x = Äußerer Radius X
outer-radius-y = Äußerer Radius Y
outset = Außenbereich
outset-path = Pfad nach außen
overflow = Überlauf
  .cut = Schnitt
  .visible = Sichtbar
override = Überschreiben Sie
padding = Polsterung
  .uniform = Uniform
page = Seite
  .next = Weiter
  .previous = Vorherige
paint = Farbe
paint-order = Auftrag malen
paint-type = Farbe Typ
palette = Palette
pan = Pan
panels = Panels
paragraph = Absatz
parameters = Parameter
parliament-hall-radius = Radius der Halle
parliament-parties = Parteien
parliament-seat-radius = Sitzradius
parliament-seats-suffix = {$count ->
  [one] seat
 *[other] seats
}
password = Passwort
password-hint = Das für die Anmeldung verwendete Passwort.
password-too-short = Das Passwort muss aus mindestens 6 Zeichen bestehen
paste = Einfügen
path = Pfad
paths = Pfade
path-nodes = Pfad-Knoten
pattern = Muster
pattern-id = Muster ID
pattern-title = Titel des Musters
patterns = Muster
pie = Kuchen
pin = Stift
pixel-shape = Pixelform
pixel-size = Pixelgröße
pixels-per-unit = Bildpunkte pro Einheit
polyline = Polylinie
polygon = Polygon
polygons = Polygone
position = Position
  .left = Links
  .right = Rechts
  .center = Zentrum
post = Beitrag
posts = Beiträge
preferences = Einstellungen
prefix = Vorsilbe
  .auto = Auto
  .custom = Benutzerdefiniert
preprocessing = Vorverarbeitung
preserve = Erhalten Sie
  .alpha = Alpha
  .stroke-width = Breite der Kontur
  .rectangle-radii = Rechteckige Radien
  .rotation = Drehung
  .aspect-ratio = Seitenverhältnis
preserve-aspect-ratio = Seitenverhältnis beibehalten
  .meet = Meet
  .slice = Slice
preset-filters = Voreingestellte Filter
  .none = Keine
  .drop-shadow = Schlagschatten
  .inner-shadow = Schatten nach innen
  .point-light = Punktlicht
  .spot-light = Spotlight
  .outline = Gliederung
  .gaussian-blur = Gaußscher Weichzeichner
  .motion-blur = Bewegungsunschärfe
  .sharpen = Schärfen
  .pixelete = Verpixeln
  .warp = Warp
  .morphology = Morphologie
  .black-and-white = Schwarz und weiß
  .grayscale = Graustufen
  .sepia = Sepia
  .saturate = Sättigung
  .hue-rotate = Farbton drehen
  .invert = Invertieren
  .brightness = Helligkeit
  .contrast = Kontrast
  .opacity = Deckkraft
  .posterize = Plakatieren
  .duotone = Duotone
  .x-ray = Röntgenbild
press = Presse
press-hint =
  <p>Die nachstehend bereitgestellten Marketing-Assets können in Artikeln, Rezensionen und Tutorials von Drittanbietern, die sich mit Boxy SVG beschäftigen, frei wiederverwendet werden.</p>
press-new-shortcut = Neue Tastenkombination drücken
pressure = Druck
preview = Vorschau
previous-tool = Vorheriges Werkzeug
price = Preis
  .free = Kostenlos
  .yearly-subscription = jährliches Abonnement
  .one-time-payment = einmalige Zahlung
price-proration-hint =
  Bei der Änderung eines bestehenden Abonnements wird der fällige Gesamtbetrag anteilig berechnet.
price-tax-hint =
  Je nach dem, wo Sie steuerlich ansässig sind, kann eine zusätzliche Mehrwertsteuer oder Umsatzsteuer anfallen.
primitive-units = Primitive Einheiten
print = Drucken
priority = Priorität
  .very-low = Sehr niedrig
  .low = Niedrig
  .normal = Normal
  .high = Hoch
  .very-high = Sehr hoch
  .critical = Kritisch
profiles = Profile
public-profile = Öffentliches Profil
puzzle-tab-size = Größe der Registerkarte
quality = Qualität
question = Frage
  .open = Öffnen
  .duplicate = Duplizieren
  .answered = Antwortet
  .out-of-date = Veraltet
questions = Fragen
  .all = Alle
  .open = Offene
  .closed = Geschlossene
quit = Beenden
radial-gradient = Radialer Gradient
radius = Radius
radius-x = Radius X
radius-y = Radius Y
rate-on-mac-app-store = Bewertung im Mac App Store
recent-files = Neueste Dateien
recent-files-hint = Begrenzen Sie die Anzahl der Dateien, die im Menü "Datei -&gt; Zuletzt geöffnet" angezeigt werden.
rectangle = Rechteck
rectangles = Rechtecke
redo = Wiederholen
reduce = Reduzieren
reduce-transform = Transformieren reduzieren
reference-point = Referenzpunkt
refresh = Auffrischen
region = Region
register = Registrieren
register-to-start-15-day-free-trial = Registrieren Sie sich, um die <strong>15-tägige kostenlose Testversion</strong> zu starten.
registration-failed = Registrierung fehlgeschlagen
relative-to = Relativ zu
  .default-view = Standard Ansicht
  .nearest-view = Nächstgelegene Ansicht
  .first-selected = Zuerst ausgewählt
  .last-selected = Zuletzt ausgewählt
  .selection = Auswahl
relevance = Relevanz
reload = Neu laden
reload-from-disk = Erneutes Laden von der Festplatte
remove = Eentfernen
remove-filter = Filter entfernen
remove-transform = Transformation entfernen
rename = Umbenennen
rendering = Rendering
reorder = Nachbestellung
reorient = Neuorientierung
repeat-strokes = Wiederholung der Konturen
reply = Antwort
required-field = Erforderliches Feld
resend = Erneut senden
reset = Zurücksetzen
reset-control-point = Kontrollpunkt zurücksetzen
reset-control-points = Kontrollpunkte zurücksetzen
reset-password = Passwort zurücksetzen
reset-password-hint = Geben Sie die E-Mail-Adresse ein, mit der Sie sich registriert haben, und folgen Sie den Anweisungen, die wir Ihnen schicken.
reset-zoom = Zurücksetzen des Zooms
resize = Größe ändern
reverse = Umkehren
reverse-gradient = Umgekehrtes Gefälle
reverse-order = Umgekehrte Reihenfolge
rgb = RGB
ring = Ring
rotate = Drehen
rotate-clockwise = Drehen +90°
rotate-counterclockwise = Drehen -90°
rotation = Drehung
  .fixed = Festgelegt
  .random = Zufällig
roughness = Rauhigkeit
roundness = Rundheit
  .random = Zufällig
  .fixed = Festgelegt
rows = Zeilen
rule = Regel
sample-from-image = Beispiel aus dem Bild
sampling = Probenahme
  .none = Keine
  .deterministic = Deterministisch
  .random = Zufällig
saturation = Sättigung
save = Speichern
save-and-host-svg-files-in-cloud = Speichern und Hosten von SVG-Dateien in der Cloud
save-as = Speichern als
save-svg-files-to-disk = SVG-Dateien auf einem Datenträger speichern
save-to-cloud-as = In der Cloud speichern unter
save-to-disk-as = Auf der Festplatte speichern unter
scalable-vector-graphics-editor = Editor für skalierbare Vektorgrafiken
scale = Skala
scale--verb = Skalieren
scale-factor = Skalierungsfaktor
screenshots = Screenshots
scripting = Skripting
search = Suche
  .all = Alle
seed = Saatgut
select-all = Alles auswählen
select-instances =
  Select {$instancesCount ->
    [unknown] instances
    [one] {$instancesCount} instance
   *[other] {$instancesCount} instances
  }
select-stop-to-recolor = Wählen Sie den Stopp zum Umfärben mit dem <span id="edit-tool-span">Werkzeug "Bearbeiten</span>
select-users =
  Select {$usersCount ->
    [unknown] users
    [one] {$usersCount} user
   *[other] {$usersCount} users
  }
selection = Auswahl
selection-mode =
  .contain = Enthält
  .intersect = Überschneiden Sie
selection-shape =
  .rectangular = Rechteckig
  .manual = Handbuch
send = Senden Sie
separator = Abscheider
services = Dienstleistungen
set-as-svg-2-filter-function = Als SVG 2-Filterfunktion einstellen
set-as-terminal-primitive = Als Terminalprimitiv festlegen
settings = Einstellungen
shadows-color = Farbe des Schattens
shape = Form
shapes = Formen
shapes-per-iteration = Formen pro Iteration
shape-to-path = Form in Pfad umwandeln
share = Teilen Sie
share-file = Datei teilen
  .url-hint = Verwenden Sie diese URL, um die Datei an andere Personen weiterzugeben oder auf anderen Websites einzubetten.
shift = Schicht
shortcut = Tastaturkürzel
shortcuts = Tastaturkürzel
  .all = Alle
  .custom = Benutzerdefinierte
  .conflicting = Widersprüchliche
show = Einblenden
show-all = Alle anzeigen
show-ids = IDs anzeigen
show-cloud-button = Schaltfläche "Cloud" anzeigen
show-install-button = Schaltfläche "Installieren" anzeigen
show-next-tab = Nächste Registerkarte anzeigen
show-previous-tab = Vorherige Registerkarte anzeigen
show-tooltips = Tooltips anzeigen
show-view-outline-above-objects = Ansichtskontur über den Objekten anzeigen
simplify = Vereinfachen Sie
simplify-path = Vereinfachen den Pfad
size = Größe
  .auto = Auto
  .random = Zufällig
  .fixed = Festgelegt
  .medium = Mittel
  .large = Groß
skew = Schräglage
skin-tone = Hautton
  .all = Alle
  .light = Licht
  .medium-light = Mittel leicht
  .medium = Mittel
  .medium-dark = Mittel dunkel
  .dark = Dunkelheit
slope = Neigung
smart-guides = Intelligente Hilfslinien
smoothing = Glättung
solid-color = Einfarbig
sort = Sortieren
  .alphabetical = Alphabetisch
  .popular = Beliebt
  .trending = Tendenz
  .latest = Neueste
  .date = Datum
  .ascending = Aufsteigend
  .descending = Absteigend
source = Quelle
source-exponent = Quellexponent
source-x = Quelle X
source-y = Quelle Y
source-z = Quelle Z
space-key = Leertaste
  .toggles-previous-tool = Schaltet das vorherige Werkzeug um
  .pans-the-canvas = Schwenkt die Leinwand
spacing = Abstand
  .letter = Buchstaben
  .word = Wörter
  .line = Zeilen
specular-constant = Spiegelnde Konstante
specular-exponent = Spiegelexponent
specular-light = Punktlicht
speed = Geschwindigkeit
spiral = Spirale
spline = Spline
  .line = Linie
  .quad-bezier = Quad Bézier
  .cubic-bezier = Kubischer Bézier
  .arc = Bogen
  .rom = Catmull-Rom
  .basis = Basis
  .levien = Levien
split = Teilen
split-nodes = Split-Knoten
split-paths = Geteilte Pfade
spokes = Speichen
spoke-targets = Ziele der Speichen
spread = Verbreitung
staff-member = Mitarbeiterin
standard-deviation = Standardabweichung
star = Stern
starred-by-me = Von mir mit Sternchen versehen
stars = Sterne
start-angle = Start-Winkel
start-point = Startpunkt
start-x = Start X
start-y = Start Y
status = Status
stitch-tiles = Fliesen nähen
stop = Zwischenfarbe
stop-color = Zwischenfarbe
stop-offset = Versatz des Anschlags
stop-opacity = Deckkraft stoppen
stretch = Dehnen
stretch-horizontally = Horizontal strecken
stretch-vertically = Vertikal strecken
strikethrough = Durchgestrichen
stroke = Kontur
stroke-color = Farbe der Kontur
stroke-opacity = Deckkraft der Kontur
stroke-to-path = Kontur in Pfad umwandeln
stroke-width = Breite der Kontur
  .non-scaling = Nicht skalierend
  .scaling = Skalierung
style = Stil
subheading = Untertitel
subject = Thema
subscribe = Abonnieren
subregion = Unterregion
subscription = Abonnement
subscription-plan = Abonnement-Plan
  .standard = Standard
  .premium = Premium
subscription-status =
  .active = Active (next payment due on {DATETIME($date, day: "numeric", month: "long", year: "numeric")})
  .active-org = Aktiv (wenden Sie sich an den Administrator Ihrer Organisation, um Änderungen vorzunehmen)
  .canceled = Canceled (effective cancellation on {DATETIME($date, day: "numeric", month: "long", year: "numeric")})
  .past-due = Überfällig (bitte aktualisieren Sie Ihre Rechnungsinformationen)
  .active-trial = Trial (ends {RELDATETIME($date)})
  .expired-trial = Trial (ended {RELDATETIME($date)})
surface-scale = Oberflächenskala
surface-shininess = Glänzende Oberfläche
svg = SVG
swap-stops = Zwischenfarben tauschen
symbol = Symbol
symbol-id = Symbol-ID
symbol-instance = Symbol-Instanz
symbol-title = Titel des Symbols
symbols = Symbole
sync-settings-between-devices = Einstellungen zwischen Geräten synchronisieren
tab-bar = Tabulatorleiste
tab-index = Registerkarte Index
tags = Tags
target = Ziel
target-x = Ziel X
target-y = Ziel Y
target-z = Ziel Z
text = Text
text-anchor = Text-Anker
  .start = Start
  .middle = Mitte
  .end = Ende
text-decoration = Textdekoration
  .underline = Unterstrichen
  .line-through = Linie-durch
  .overline = Überschrift
  .remove-underline = Unterstriche entfernen
  .remove-line-through = Durchgehende Linie entfernen
  .remove-overline = Überschrift entfernen
text-on-path = Text auf Pfad
text-path = Text Pfad
text-transform = Text umwandeln
  .capitalize = Großschreiben
  .uppercase = Großbuchstaben
  .lowercase = Kleinbuchstaben
  .none = Keine
theme = Thema
thickness = Dicke
time = Zeit
title = Titel
tools = Werkzeuge
tour-ui =
  .title = Intuitive Benutzeroberfläche
  .description =
    <p>Boxy SVG basiert auf der Idee, dass Benutzeroberflächen aus dem Weg geräumt werden sollten. Es gibt keinen überfüllten Arbeitsbereich mit sich überlappenden Dialogen oder Dutzenden von geöffneten Paletten und Symbolleisten. Ihre Illustration steht im Mittelpunkt.</p>
    <p>Ob es sich um die Bearbeitung von Formen oder die Anpassung von Farbverlaufsfüllungen handelt, die <strong>meisten</strong> Aktionen finden <strong>direkt auf der</strong> Leinwand statt. Die Feinsteuerung der Änderungen erfolgt über Bedienfelder, die Sie mit einem einzigen Klick oder Tastendruck ein- und ausblenden können.</p>
    <p>Viele Funktionen sind über <strong>Tastenkombinationen</strong> zugänglich, die Sie nach Ihren Wünschen anpassen können, was besonders nützlich ist, wenn Sie durch die jahrelange Arbeit mit anderen Vektorgrafik-Editoren bereits über ein gutes Muskelgedächtnis verfügen.</p>
tour-svg =
  .title = Native SVG-Unterstützung
  .description =
    <p>Boxy SVG verwendet <strong>Scalable Vector Graphics (SVG)</strong> als natives Dokumentenformat. Mit SVG gibt es keine Herstellerbindung. Es ist ein <strong>offener Standard</strong> für das Web, genau wie HTML5 und CSS, der vom World Wide Web Consortium entwickelt wurde und an dem zahlreiche Akteure aus verschiedenen Branchen beteiligt sind.</p>
    <p>Sie brauchen Ihr Originaldokument nicht in einem proprietären Dateiformat zu speichern, ständig nach SVG zu exportieren und es jedes Mal zu bereinigen, bevor Sie es verwenden können. Erstellen Sie einfach eine neue Illustration oder öffnen Sie eine bestehende, zeichnen Sie, speichern Sie. Das ist alles.</p>
    <p>Alle Ihre mit Boxy SVG erstellten Dokumente sind <strong>100% standardkonform</strong>. Sie können mit anderer Autorensoftware bearbeitet werden und werden in den meisten Desktop- und mobilen Webbrowsern korrekt wiedergegeben, da Boxy SVG <strong>von der Chromium-Engine unterstützt</strong> wird.</p>
    <p>Das Programm macht es auch einfach, Illustrationen zu erstellen, die sofort für die Veröffentlichung im Web bereit sind. Boxy SVG verfolgt automatisch nicht verwendete Definitionen wie Farbverläufe und Muster und entfernt sie, um den endgültigen SVG-Code sauber und frei von Ballast zu halten.</p>
    <p>Zusätzliche Optionen geben Ihnen die Kontrolle über die Einrückung des SVG-Codes sowie über die Geometrie- und Transformationspräzision, die auch die Größe der endgültigen Dokumente beeinflusst.</p>
tour-filters =
  .title = Filter-Effekte
  .description =
    <p>Wenden Sie visuelle Effekte auf Bitmap- und Vektoren-Objekte gleichermaßen mit SVG-Filtern an. Boxy SVG enthält <strong>mehr als 20 voreingestellte Filter</strong> für gängige Anwendungsfälle wie:</p>
    <ul>
      <li>Farbmanipulation, z.B. "Graustufen", "Sepia" und "Duotone"</li>
      <li>Verzerrung, z.B. "Bewegungsunschärfe", "Warp" und "Morphologie"</li>
      <li>Dekoration, z. B. "Schlagschatten", "Punktlicht" und "Umriss".</li>
    </ul>
    <p>Alle voreingestellten Filter haben <strong>benutzerfreundliche, beschreibende Einstellungen</strong>. Alle Änderungen, die Sie vornehmen, werden sofort auf der Leinwand gerendert und können später jederzeit nachgebessert werden. Öffnen Sie einfach das Bedienfeld "Komposition", wählen Sie ein Objekt mit einem Filter aus, und nehmen Sie weitere Anpassungen vor.</p>
    <p>Sie können sogar noch einen Schritt weiter gehen und <strong>Ihre eigenen Filter erstellen</strong>. Boxy SVG bietet eine einfach zu bedienende Schnittstelle, um komplexe Effekte aus einfachen Primitiven zu erstellen. Öffnen Sie das Bedienfeld "Definitionen", erstellen Sie einen benutzerdefinierten SVG-Filter, fügen Sie einige Filterbausteine hinzu und ordnen Sie diese in einem Diagramm mit sofortiger Vorschau auf der Leinwand an.</p>
    <p>Alle SVG-Filter werden von den <strong>meisten Webbrowsern nativ unterstützt</strong>. Sie müssen Ihre Illustrationen nicht in Bitmaps exportieren oder komplexen JavaScript-Code schreiben, um sie auf einer Website korrekt anzuzeigen.</p>
tour-typography =
  .title = Fortgeschrittene Typografie
  .description =
    <p>Erstellen Sie schöne Beschriftungen mit einer der <strong>über 1.000 Schriften</strong> aus dem Google Fonts-Verzeichnis oder importieren und betten Sie <strong>WOFF-, TTF- und OTF-Schriftdateien</strong> von Ihrer Festplatte ein.</p>
    <p>Übernehmen Sie die vollständige Kontrolle über die Gestaltung von Text. Wenden Sie Unterstrichenes, Durchgestrichenes und Überstrichenes an, nutzen Sie verschiedene Optionen für die Groß- und Kleinschreibung, wenden Sie flache, verlaufende oder Muster-Füllungen und Konturen an.</p>
    <p>Verwenden Sie die <strong>Abstandsoptionen</strong>, um den Abstand zwischen allen Zeichen, Wörtern und Zeilen zu steuern, oder verwenden Sie das Bearbeitungswerkzeug, um jede Glyphe frei zu positionieren.</p>
    <p>Erstellen Sie <strong>Text auf</strong> Pfaden mit nur einem Klick und passen Sie den Versatz an, um die optimale Position des Textes auf der Kurve zu finden.</p>
tour-developer =
  .title = Werkzeuge für Entwickler
  .description =
    <p><strong>Überprüfen Sie den zugrunde liegenden SVG- und CSS-Code</strong> ganz einfach mit dem integrierten Bedienfeld "Elemente". Das Prinzip ist dasselbe wie bei den Werkzeugen für Webentwickler, die in gängigen Webbrowsern verfügbar sind.</p>
    <p>Sie können das Bedienfeld "Elemente" verwenden, um <strong>sowohl SVG- als auch CSS-Code direkt vor Ort zu bearbeiten</strong>. Die Leinwand und der Code-Inspektor sind perfekt aufeinander abgestimmt: Wenn Sie in einem der beiden Bereiche eine Änderung vornehmen, wird der Inhalt des anderen automatisch aktualisiert.</p>
    <p>Der Inspektor ermöglicht auch das <strong>Kopieren und Einfügen von SVG-Codefragmenten</strong> zwischen Boxy SVG und externen Programmen wie Texteditoren.</p>
tour-export =
  .title = Optionen für den Export
  .description =
    <p>Übertragen Sie Ihre Arbeit einfach in Dateiformate wie <strong>PNG, JPEG, GIF, WebP und PDF</strong>. Für jeden unterstützten Dateityp bietet Boxy SVG formatspezifische Exportoptionen wie Komprimierung, Auflösung, Hintergrundfarbe und viele andere.</p>
    <p>Beim Speichern in SVG können Sie die Dateigröße <strong>minimieren</strong>, indem Sie optional eingebettete Schriften und nicht standardmäßige Markup-Elemente entfernen.</p>
    <p>Für alle Dateitypen können Sie den Exportbereich manuell festlegen oder schnell zwischen dem Export aller Objekte und dem Export der aktuellen Auswahl wechseln.</p>
    <p>Der Bereich "Vorschau" bietet einen Überblick über das endgültige Rendering und berechnet die Dateigröße, um Sie bei der Optimierung für das Web zu unterstützen.</p>
tour-library =
  .title = Vermögen Bibliothek
  .description =
    <p>Greifen Sie auf Millionen hochwertiger <strong>Stockfotos und Vektorillustrationen</strong> von <a
    rel="noopener" href="https://pixabay.com/">Pixabay</a>, Hunderte von <strong>Farbpaletten</strong>von <a rel="noopener" href="https://colorhunt.co/">ColorHunt</a> und über tausend <strong>Schriften</strong> aus dem <a rel="noopener" href="https://fonts.google.com/">Google Fonts-Verzeichnis</a>zu.</p>
    <p>Benötigen Sie eine serifenlose Schrift mit Zeichen aus dem griechischen Alphabet oder vielleicht alle Vektoren mit Schuhen aus der Kategorie "Sport"? Suchen Sie nach einem Stichwort, um eine erste Auswahl zu treffen, und wenden Sie dann einen Schnellfilter an, um die Suchergebnisse einzugrenzen. Wenn Sie das gewünschte Bild gefunden haben, <strong>ziehen Sie</strong>es einfach <strong>per Drag &amp; Drop</strong>auf die Leinwand, um es zu verwenden.</p>
    <p>Alle Assets sind unter <strong>freien Lizenzen</strong> veröffentlicht und können in kommerziellen Projekten frei verwendet werden, ohne dass Lizenzgebühren anfallen.</p>
tour-tracing =
  .title = Bildverfolgung
  .description =
    <p>Boxy SVG bietet bequeme Werkzeuge zur Erstellung von Vektorgrafiken aus Bitmaps, mit einer Vielzahl von stilistischen Ansätzen.</p>
    <p>Verwenden Sie den <strong>Generator</strong> "Vektorisieren", um eine skalierbare Zeichnung zu erstellen, die der ursprünglichen Bitmap so nahe wie möglich kommt. Wählen Sie eine Voreinstellung wie "Graustufen" oder "Plakatiert" oder verwenden Sie die erweiterten Optionen, die Ihnen volle Kontrolle über das Vektorisieren bieten.</p>
    <p>Wählen Sie den <strong>Generator Pixelate</strong>, um ein Muster aus großen Farbblöcken zu erzeugen, das dem Mosaikeffekt ähnelt.</p>
    <p>Verwenden Sie den <strong>Generator</strong> " <strong>Triangulieren"</strong> oder " <strong>Primitivisieren"</strong>, um eine skalierbare Variante des ursprünglichen Bitmap-Bildes mit Annäherung an geometrische Grundformen wie Dreiecke zu erstellen.</p>
tour-symbols =
  .title = Wiederverwendbare Symbole
  .description =
    <p>Verwenden Sie das Panel "Definitionen", um <strong>SVG-Symbole zu verwalten</strong>. Mit nur ein oder zwei Klicks können Sie neue Symbole erstellen und bearbeiten, ihre IDs und Titel umbenennen.</p>
    <p>Ziehen Sie ein Symbol aus dem Bedienfeld "Definitionen" auf die Leinwand, um seine Instanz zu erstellen. Alle Instanzen eines Symbols werden automatisch aktualisiert, sobald Sie das Original ändern.</p>
    <p>Boxy SVG ist auch in der Lage, <strong>SVG-Sprites</strong> zu bearbeiten, die verwendet werden, um komplette Symbolsätze im Web zu speichern. Bei sehr großen Sprites können Sie die Filteroption verwenden, um Symbole anhand ihrer Namen oder IDs zu finden.</p>
    <p>Die erweiterte Kontrolle über die Ansichtsbox <strong>und das</strong> Ansichtsfenster jedes Symbols wird durch das Panel "Geometrie" gewährleistet.</p>
transform = Transformieren
transform-gradient = Gradient transformieren
transform-pattern = Muster transformieren
transform-precision = Präzision transformieren
transform-precision-hint = Genauigkeit, in Anzahl der Dezimalstellen, die vom Attribut <code>transform</code> verwendet werden soll.
transparency = Transparenz
treat-selection-as-group = Auswahl als Gruppe behandeln
triangle = Dreieck
triangles = Dreiecke
try-redefining-search-criteria = Versuchen Sie, Ihre Suchkriterien neu zu definieren
tutorials = Tutorials
tutorial-selecting-objects =
  .title = Auswählen von Objekten
  .description = Wählen Sie ein oder mehrere Objekte aus.
tutorial-transforming-objects =
  .title = Objekte umwandeln
  .description = Verschieben, Skalieren, Neigen und Drehen von Objekten.
tutorial-paths =
  .title = Pfade
  .description = Zeichnen und Bearbeiten von Pfaden.
tutorial-shapes =
  .title = Formen
  .description = Zeichnen und bearbeiten Sie Formen wie Rechtecke, Kreise, Ellipsen, Sterne und mehr.
tutorial-fill-and-stroke =
  .title = Füllung und Kontur
  .description = Ändern Sie die Füllung und Kontur eines Objekts.
tutorial-compositing =
  .title = Komposition
  .description = Wenden Sie Filter, Mischmodi, Beschneidungspfade und Masken auf ein Objekt an.
tutorial-text-and-fonts =
  .title = Text und Schriften
  .description = Erstellen und bearbeiten Sie Text.
tutorial-symbols =
  .title = Symbole
  .description = Erstellen und bearbeiten Sie wiederverwendbare Symbole.
tutorial-views =
  .title = Ansichten
  .description = Standard- und benutzerdefinierte Ansichten manipulieren.
tutorial-metadata =
  .title = Metadaten
  .description = Bearbeiten Sie Titel, Beschreibung, ID und andere Metadaten eines Objekts.
tutorial-library =
  .title = Bibliothek
  .description = Holen Sie sich Fotos, Vektoren, Farbpaletten und Schriften aus einer öffentlichen Bibliothek.
tutorial-export =
  .title = Exportieren
  .description = Exportieren Sie Ihr Bildmaterial in PNG, JPEG, GIF, WebP, SVG, SVGZ, HTML oder PDF.
type = Typ
typography = Typografie
ui = UI
unclip = Unclip
underline = Unterstrichen
undo = Rückgängig
ungroup = Ungruppieren
unhide = einblenden
unhide-all = Alle ausblenden
units = Einheiten
  .user = Benutzer
  .object-bbox = Objekt-Begrenzungsrahmen
  .stroke-width = Breite der Kontur
  .px = Bildpunkte
  .cm = Zentimeter
  .mm = Millimeter
  .in = Zoll
  .pt = Punkte
  .pc = Picas
  .q = Viertelmillimeter
unlink = Trennen
unlock = freischalten
unlock-all = Alle freischalten
unmask = Demaskieren
unordered-list = Unsortierte Liste
unpin = Unpin
unvote = Nicht abstimmen
update-billing = Rechnung aktualisieren
updated-time = Aktualisierte Zeit
uploader = Uploader
upvote = Hochwählen
upvoted-by-me = Von mir hochgewählt
url = URL
user = Benutzer
user-not-found = Benutzer nicht gefunden
users = Benutzer
users-count-hint =
  <p>Anzahl der Benutzer, die zu Ihrer Organisation gehören und die App gleichzeitig nutzen können sollen.</p>
  <p>Sie können den Benutzern jederzeit Lizenzen zuweisen und die Zuweisung aufheben, indem Sie ihre E-Mail-Adressen unter <a id="auth-anchor" href="?dialog=settings→auth">"Einstellungen → Authentifizierung"</a> eingeben.</p>
users-emails-hint =
  Geben Sie die E-Mail-Adressen der Benutzer ein, die zu Ihrer Organisation gehören. Um die zulässige Anzahl der Benutzer zu erhöhen, passen Sie bitte Ihren <a id="subscription-anchor" href="?dialog=settings→subscription">Abonnementplan</a> an.
value = Wert
values = Werte
variance = Abweichung
vectorize-preset = Voreinstellung
  .default = Standard
  .black-and-white = Schwarz und weiß
  .grayscale = Graustufen
  .posterized = Plakatiert
  .curvy = Kurvenreich
  .sharp = Scharf
  .detailed = Ausführlich
  .smoothed = geglättet
vectrize-rendering =
  .line-filter = Aktivieren des Linienfilters zur Rauschunterdrückung
  .ignore-white = Weiß ignorieren
vectorize-tracing = Rückverfolgung
  .l-treshold = L-Schwelle
  .q-treshold = Q-Schwelle
  .path-omit = Pfad auslassen
  .enhance = Verbessern Sie rechtwinklige Ecken
vectors = Vektoren
verify = Überprüfen Sie
verify-your-email-address = Überprüfen Sie Ihre E-Mail-Adresse
  .detail =
    <p>Please follow the link we have sent to <strong>{$email}</strong> to verify this email address.
    <p><strong>Note</strong>: It might take up to 30 seconds for the changes to propagate.</p>
version = Version
  .pending = in Vorbereitung
view = Ansicht
  .default = Standard
view-box = Ansichtsbox
view-on = View on {$provider}
viewport = Ansichtsfenster
  .fixed = Festgelegt
  .responsive = Ansprechbar
viewport-space = Koordinatenraum des Ansichtsfenster
views = Ansichten
volume-discount = Mengenrabatt
  .none = Keine
volume-discount-hint =
  <p>Ein Rabatt wird gewährt, wenn Sie ein Abonnement für mehrere Benutzer erwerben:</p>
  <ul>
    <li>10% Rabatt - für 10 oder mehr Benutzer</li>
    <li>20% Rabatt - für 30 oder mehr Benutzer</li>
    <li>30% Rabatt - für 100 oder mehr Benutzer</li>
  </ul>
votes = Abstimmungen
warning = Warnung
watch = Siehe
watch-thread = Gewinde beobachten
  .detail = Sie werden per E-Mail benachrichtigt, wenn neue Kommentare erscheinen.
watched-by-me = Von mir beobachtet
website = Website
website-hint = URL zu Ihrer persönlichen oder Unternehmens-Website.
web-app = Web-Applikation
widgets-size = Widget-Größe
width = Breite
window = Fenster
word-spacing = Wortabstand
working-size = Arbeitsgröße
year = Jahr
zoom-in = Einzoomen
zoom-out = Auszoomen
zoom-window = Fenster vergrößern
zoom-to-fit-all-objects = Zoomen, um alle Objekte einzupassen
zoom-to-fit-all-primitives = Zoomen, um alle Primitive einzupassen
zoom-to-fit-all-views = Einzoomen, um alle Ansichten anzupassen
zoom-to-fit-selected-objects = Zoomen, um ausgewählte Objekte einzupassen
